### ISSUE TITLE
Idea: Procedural Space Adventure

### ISSUE THREAD

**Issue by bentok** [bentok/invisible#5]
You're a a space ship holding some valuable information and you must navigate procedurally generated sectors with the goal of delivering this information. The game is more complex but I think with that idea could take that premise to make a game where you have to make good use of some invisibility mechanic for your space ship navigating some galaxy

**Comment by bentok** [comment]
I think this would be a fun one to do, as procedural generation would add immediate depth.

+1 from me.

**Comment by paulmojicatech** [comment]
Plus one for me too.

**Comment by D3Castro** [comment]
+1 here as well. How should we split up the game content?

**Comment by bentok** [comment]
Good questions about splitting up content. I'll close the current kanban board and we can create a new one for splitting things up.
